# Generated by Django 6.0.3 on 2026-03-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='cnpj',
        ),
    ]
