# Generated by Django 6.0.3 on 2026-03-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_remove_unidade_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de Equipamento')),
            ],
            options={
                'verbose_name': 'Tipo de Equipamento',
                'verbose_name_plural': 'Tipos de Equipamento',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['nome'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Equipamento')),
                ('status', models.CharField(choices=[('uso', 'Em Uso'), ('ocioso', 'Ocioso'), ('manutencao', 'Em Manutenção')], default='uso', max_length=50, verbose_name='Status do Equipamento')),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamentos', to='control.unidade')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamentos', to='control.tipoequipamento')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['nome'],
            },
        ),
    ]
