# Generated by Django 6.0.3 on 2026-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_tipoequipamento_alter_unidade_options_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor do Equipamento'),
        ),
    ]
