# Generated by Django 6.0.3 on 2026-03-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_equipamento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='usuario',
            field=models.TextField(blank=True, default='Dpto/Unidade', max_length=255, null=True, verbose_name='Usuário Responsável'),
        ),
    ]
