# Generated by Django 6.0.3 on 2026-03-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_remove_equipamento_usuario_equipamento_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código'),
        ),
    ]
