# Generated by Django 6.0.3 on 2026-03-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_unidade_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ['codigo'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='equipamento',
            name='classe',
            field=models.CharField(choices=[('cozinha', 'Cozinha Industrial'), ('tic', 'TIC')], default='tic', max_length=20, verbose_name='Classe do Equipamento'),
        ),
    ]
