# Generated by Django 6.0.3 on 2026-03-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_alter_unidade_options_equipamento_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=20, verbose_name='Classe de Equipamento')),
            ],
            options={
                'verbose_name': 'Classe de Equipamento',
                'verbose_name_plural': 'Classes de Equipamento',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipamentos', to='control.classeequipamento'),
        ),
    ]
