# Generated by Django 6.0.3 on 2026-03-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_classeequipamento_alter_equipamento_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='classe',
        ),
    ]
