# Generated by Django 6.0.3 on 2026-03-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_remove_equipamento_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipamento',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tipos', to='control.classeequipamento'),
        ),
    ]
