# Generated by Django 6.0.3 on 2026-03-12 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_tipoequipamento_classe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoequipamento',
            options={'ordering': ['classe', 'nome'], 'verbose_name': 'Tipo de Equipamento', 'verbose_name_plural': 'Tipos de Equipamento'},
        ),
        migrations.CreateModel(
            name='HistoricoTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_origem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável Anterior')),
                ('responsavel_destino', models.CharField(blank=True, max_length=255, null=True, verbose_name='Novo Responsável')),
                ('motivo', models.TextField(verbose_name='Motivo / Observação')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_transferencias', to='control.equipamento')),
                ('unidade_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_entrada', to='control.unidade')),
                ('unidade_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_saida', to='control.unidade')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Transferência',
                'verbose_name_plural': 'Históricos de Transferências',
                'ordering': ['-data_transferencia'],
            },
        ),
    ]
