# Generated by Django 6.0.3 on 2026-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_alter_manutencao_options_manutencao_unidade_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='classeequipamento',
            name='sigla',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='classeequipamento',
            name='nome',
            field=models.CharField(max_length=20, unique=True, verbose_name='Classe de Equipamento'),
        ),
    ]
