# Generated by Django 6.0.3 on 2026-04-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_classeequipamento_sigla_alter_classeequipamento_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tag',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Tag Patrimonial'),
        ),
    ]
